import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: '2020 Mercedes-Benz GLC 63S AMG GLC 63S',
      slug: 'mercedes-benz',
      category: 'SUV',
      image: '/images/cars/amg.jpg',
      isFeatured: true,
      featuredImage: '/images/cars/amg.jpg',
      price: 500,
      brand: 'Mercedes',
      rating: 4.9,
      numReviews: 10,
      countInStock: 20,
      description: 'MERCEDES BENZ INSPECTION AVAILABLE UPON REQUEST!! ***CARFAX VERIFIED AND AVAILABLE UPON REQUEST*** AUTO, BLACK OVER BLACK AND RED LEATHER INT, A\C, CD,  AIR CONDITIONING, CRUISE CTRL, CLIMATE CONTROL, TILT-WHEEL, NAVIGAION SYSTEM, BACK-UP CAMERA, BLUETOOTH, TRACTION CONTROL, AND MORE! ONLY 154, 050 KM! ',
    },
    {
      name: '2014 Bentley Continental Flying Spur ',
      slug: 'bentley-continental',
      category: 'Sedan',
      image: '/images/cars/bentley-continental-flying-spur-1.jpg',
      isFeatured: true,
      featuredImage: '/images/cars/bentley-continental-flying-spur-1.jpg',
      price: 995,
      brand: 'Bentley',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'BENTLEY INSPECTION AVAILABLE UPON REQUEST!! ***CARFAX VERIFIED UPON REQUEST*** AUTO,  PINK OVER WHITE LEATHER INT, AIR CONDITIONING, CRUISE CTRL, CLIMATE CONTROL, NAVIGATION SYSTEM,  CAMERA, ROOF,TILT WHEEL, BLUETOOTH, TRACTION CONTROL, AND MORE! ONLY  58,525KM! ',
    },
    {
      name: '2015 Toyota RAV4',
      slug: 'toyota-rav4',
      category: 'SUV',
      image: '/images/cars/2015_Toyota_RAV4_Icon_D4D_Automatic_2.2_Front.jpg',
      price: 800,
      brand: 'Toyota',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'TOYOTA INSPECTION AVAILABLE UPON REQUEST!! ***CARFAX VERIFIED AVAILABLE UPON REQUEST*** AUTO, ORANGE OVER BLACK LEATHER  INT, A\C, CD, PM, PDL, AIR CONDITIONING, CRUISE CTRL, CLIMATE CONTROL, TILT WHEEL, ,BLUETOOTH, TRACTION CONTROL, AND MORE! ONLY  79,998KM!',
    },
    {
      name: '2017 Audi Q7',
      slug: 'audi-q7',
      category: 'SUV',
      image: '/images/cars/audi-q7.jpg',
      price: 500,
      brand: 'Audi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'AUDI INSPECTION AVAILABLE UPON REQUEST!! ***CARFAX VERIFIED UPON REQUEST*** AUTO,  WHITE OVER BLACK LEATHER INT, AIR CONDITIONING, CRUISE CTRL, CLIMATE CONTROL, TILT WHEEL,, BACK UP CAMERA, TECHNIK, S LINE, 360 CAMERA, NAVIGATION, BLUETOOTH, TRACTION CONTROL, AND MORE! ONLY  169,998  KM! ',
    },
    {
      name: '2015 Honda Civic EX',
      slug: 'honda-civic',
      category: 'Sedan',
      image: '/images/cars/honda-civic-ex.jpg',
      price: 495,
      brand: 'HONDA',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Honda lovers check out this Civic. We have a Gorgeous 2015 Honda Civic, This one has most of the Honda features you could wish for. People who know Hondas love them for the reliable economical drive,Low maintenance cost, Manual transmission for better control These vehicles are hard to come by,',
    },
    {
      name: '2010 Hyundai Elantra GLS',
      slug: 'hyundai-elantra',
      category: 'Sedan',
      image: '/images/cars/Hyundai-elantra.jpg',
      price: 275,
      brand: 'Hyundai',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Anti-Lock Brakes Power Steering 4-Wheel Disc Brakes Driver Air Bag Passenger Air Bag Side Air Bag Traction Control Heated Mirrors Rear Window Defrost Brake Assist Stability Control Child Safety Locks Rear Head Air Bag Front Head Air Bag Passenger Air Bag Sensor',
    },
  ],
  productsPro: [
    {
      name: '2020 Mercedes-Benz GLC 63S AMG GLC 63S',
      slug: 'mercedes-benz',
      category: 'SUV',
      image: '/images/cars/amg.jpg',
      isFeatured: true,
      featuredImage: '/images/cars/amg.jpg',
      price: 500,
      brand: 'Mercedes',
      rating: 4.9,
      numReviews: 10,
      countInStock: 20,
      description: 'MERCEDES BENZ INSPECTION AVAILABLE UPON REQUEST!! ***CARFAX VERIFIED AND AVAILABLE UPON REQUEST*** AUTO, BLACK OVER BLACK AND RED LEATHER INT, A\C, CD,  AIR CONDITIONING, CRUISE CTRL, CLIMATE CONTROL, TILT-WHEEL, NAVIGAION SYSTEM, BACK-UP CAMERA, BLUETOOTH, TRACTION CONTROL, AND MORE! ONLY 154, 050 KM! ',
    },
    {
      name: '2014 Bentley Continental Flying Spur ',
      slug: 'bentley-continental',
      category: 'Sedan',
      image: '/images/cars/bentley-continental-flying-spur-1.jpg',
      isFeatured: true,
      featuredImage: '/images/cars/bentley-continental-flying-spur-1.jpg',
      price: 995,
      brand: 'Bentley',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'BENTLEY INSPECTION AVAILABLE UPON REQUEST!! ***CARFAX VERIFIED UPON REQUEST*** AUTO,  PINK OVER WHITE LEATHER INT, AIR CONDITIONING, CRUISE CTRL, CLIMATE CONTROL, NAVIGATION SYSTEM,  CAMERA, ROOF,TILT WHEEL, BLUETOOTH, TRACTION CONTROL, AND MORE! ONLY  58,525KM! ',
    },
    {
      name: '2017 Audi Q7',
      slug: 'audi-q7',
      category: 'SUV',
      image: '/images/cars/audi-q7.jpg',
      price: 500,
      brand: 'Audi',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'AUDI INSPECTION AVAILABLE UPON REQUEST!! ***CARFAX VERIFIED UPON REQUEST*** AUTO,  WHITE OVER BLACK LEATHER INT, AIR CONDITIONING, CRUISE CTRL, CLIMATE CONTROL, TILT WHEEL,, BACK UP CAMERA, TECHNIK, S LINE, 360 CAMERA, NAVIGATION, BLUETOOTH, TRACTION CONTROL, AND MORE! ONLY  169,998  KM! ',
    },
  ],
};
export default data;
